/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pkcs11_rpc.h"

bool_t
xdr_pkcs11_int(xdrs, objp)
	XDR *xdrs;
	pkcs11_int *objp;
{

	if (!xdr_int64_t(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_rv_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_rv_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_slot_id_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_slot_id_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_mechanism_type_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_mechanism_type_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_session_handle_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_session_handle_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_user_type_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_user_type_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_state_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_state_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_object_handle_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_object_handle_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_object_class_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_object_class_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_hw_feature_type_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_hw_feature_type_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_key_type_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_key_type_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_certificate_type_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_certificate_type_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_attribute_type_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_attribute_type_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_flags_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_flags_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_notification_t(xdrs, objp)
	XDR *xdrs;
	rpc_ck_notification_t *objp;
{

	if (!xdr_pkcs11_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_opaque_data(xdrs, objp)
	XDR *xdrs;
	opaque_data *objp;
{

	if (!xdr_bytes(xdrs, (char **)&objp->opaque_data_val, (u_int *)&objp->opaque_data_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_version(xdrs, objp)
	XDR *xdrs;
	rpc_ck_version *objp;
{

	if (!xdr_bytes(xdrs, (char **)&objp->major.major_val, (u_int *)&objp->major.major_len, 1))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->minor.minor_val, (u_int *)&objp->minor.minor_len, 1))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_info(xdrs, objp)
	XDR *xdrs;
	rpc_ck_info *objp;
{

	if (!xdr_rpc_ck_version(xdrs, &objp->rpc_ck_info_cryptoki_version))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_info_manufacturer_id.rpc_ck_info_manufacturer_id_val, (u_int *)&objp->rpc_ck_info_manufacturer_id.rpc_ck_info_manufacturer_id_len, 32))
		return (FALSE);
	if (!xdr_rpc_ck_flags_t(xdrs, &objp->rpc_ck_info_flags))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_info_library_description.rpc_ck_info_library_description_val, (u_int *)&objp->rpc_ck_info_library_description.rpc_ck_info_library_description_len, 32))
		return (FALSE);
	if (!xdr_rpc_ck_version(xdrs, &objp->rpc_ck_info_library_version))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_slot_info(xdrs, objp)
	XDR *xdrs;
	rpc_ck_slot_info *objp;
{

	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_slot_info_slot_description.rpc_ck_slot_info_slot_description_val, (u_int *)&objp->rpc_ck_slot_info_slot_description.rpc_ck_slot_info_slot_description_len, ~0))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_slot_info_manufacturer_id.rpc_ck_slot_info_manufacturer_id_val, (u_int *)&objp->rpc_ck_slot_info_manufacturer_id.rpc_ck_slot_info_manufacturer_id_len, ~0))
		return (FALSE);
	if (!xdr_rpc_ck_flags_t(xdrs, &objp->rpc_ck_slot_info_flags))
		return (FALSE);
	if (!xdr_rpc_ck_version(xdrs, &objp->rpc_ck_slot_info_hardware_version))
		return (FALSE);
	if (!xdr_rpc_ck_version(xdrs, &objp->rpc_ck_slot_info_firmware_version))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_token_info(xdrs, objp)
	XDR *xdrs;
	rpc_ck_token_info *objp;
{

	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_token_info_label.rpc_ck_token_info_label_val, (u_int *)&objp->rpc_ck_token_info_label.rpc_ck_token_info_label_len, 32))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_token_info_manufacturer_id.rpc_ck_token_info_manufacturer_id_val, (u_int *)&objp->rpc_ck_token_info_manufacturer_id.rpc_ck_token_info_manufacturer_id_len, 32))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_token_info_model.rpc_ck_token_info_model_val, (u_int *)&objp->rpc_ck_token_info_model.rpc_ck_token_info_model_len, 16))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_token_info_serial_number.rpc_ck_token_info_serial_number_val, (u_int *)&objp->rpc_ck_token_info_serial_number.rpc_ck_token_info_serial_number_len, 16))
		return (FALSE);
	if (!xdr_rpc_ck_flags_t(xdrs, &objp->rpc_ck_token_info_flags))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_max_session_count))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_session_count))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_max_rw_session_count))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_rw_session_count))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_max_pin_len))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_min_pin_len))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_total_public_memory))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_free_public_memory))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_total_private_memory))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_token_info_free_private_memory))
		return (FALSE);
	if (!xdr_rpc_ck_version(xdrs, &objp->rpc_ck_token_info_hardware_version))
		return (FALSE);
	if (!xdr_rpc_ck_version(xdrs, &objp->rpc_ck_token_info_firmware_version))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_token_info_utc_time.rpc_ck_token_info_utc_time_val, (u_int *)&objp->rpc_ck_token_info_utc_time.rpc_ck_token_info_utc_time_len, 16))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_mechanism(xdrs, objp)
	XDR *xdrs;
	rpc_ck_mechanism *objp;
{

	if (!xdr_rpc_ck_mechanism_type_t(xdrs, &objp->rpc_ck_mechanism_mechanism))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_mechanism_parameter.rpc_ck_mechanism_parameter_val, (u_int *)&objp->rpc_ck_mechanism_parameter.rpc_ck_mechanism_parameter_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_session_info(xdrs, objp)
	XDR *xdrs;
	rpc_ck_session_info *objp;
{

	if (!xdr_rpc_ck_slot_id_t(xdrs, &objp->rpc_ck_session_info_slot_id))
		return (FALSE);
	if (!xdr_rpc_ck_state_t(xdrs, &objp->rpc_ck_session_info_state))
		return (FALSE);
	if (!xdr_rpc_ck_flags_t(xdrs, &objp->rpc_ck_session_info_flags))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_session_info_device_error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_mechanism_info(xdrs, objp)
	XDR *xdrs;
	rpc_ck_mechanism_info *objp;
{

	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_mechanism_info_min_key_size))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_mechanism_info_max_key_size))
		return (FALSE);
	if (!xdr_rpc_ck_flags_t(xdrs, &objp->rpc_ck_mechanism_info_flags))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_attribute(xdrs, objp)
	XDR *xdrs;
	rpc_ck_attribute *objp;
{

	if (!xdr_rpc_ck_attribute_type_t(xdrs, &objp->rpc_ck_attribute_type))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_attribute_value.rpc_ck_attribute_value_val, (u_int *)&objp->rpc_ck_attribute_value.rpc_ck_attribute_value_len, ~0))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->rpc_ck_attribute_value_len))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_attribute_array(xdrs, objp)
	XDR *xdrs;
	rpc_ck_attribute_array *objp;
{

	if (!xdr_array(xdrs, (char **)&objp->rpc_ck_attribute_array_val, (u_int *)&objp->rpc_ck_attribute_array_len, ~0, sizeof(rpc_ck_attribute), (xdrproc_t)xdr_rpc_ck_attribute))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rpc_ck_date(xdrs, objp)
	XDR *xdrs;
	rpc_ck_date *objp;
{

	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_date_year.rpc_ck_date_year_val, (u_int *)&objp->rpc_ck_date_year.rpc_ck_date_year_len, 4))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_date_month.rpc_ck_date_month_val, (u_int *)&objp->rpc_ck_date_month.rpc_ck_date_month_len, 2))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->rpc_ck_date_day.rpc_ck_date_day_val, (u_int *)&objp->rpc_ck_date_day.rpc_ck_date_day_len, 2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetSlotList(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetSlotList *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetSlotList_rv))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->c_GetSlotList_slot_list.c_GetSlotList_slot_list_val, (u_int *)&objp->c_GetSlotList_slot_list.c_GetSlotList_slot_list_len, ~0, sizeof(rpc_ck_slot_id_t), (xdrproc_t)xdr_rpc_ck_slot_id_t))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->c_GetSlotList_count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetSlotInfo(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetSlotInfo *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetSlotInfo_rv))
		return (FALSE);
	if (!xdr_rpc_ck_slot_info(xdrs, &objp->c_GetSlotInfo_slot_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetTokenInfo(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetTokenInfo *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetTokenInfo_rv))
		return (FALSE);
	if (!xdr_rpc_ck_token_info(xdrs, &objp->c_GetTokenInfo_token_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetInfo(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetInfo *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetInfo_rv))
		return (FALSE);
	if (!xdr_rpc_ck_info(xdrs, &objp->c_GetInfo_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_WaitForSlotEvent(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_WaitForSlotEvent *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_WaitForSlotEvent_rv))
		return (FALSE);
	if (!xdr_rpc_ck_slot_id_t(xdrs, &objp->c_WaitForSlotEvent_count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_OpenSession(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_OpenSession *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_OpenSession_rv))
		return (FALSE);
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->c_OpenSession_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetMechanismList(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetMechanismList *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetMechanismList_rv))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->c_GetMechanismList_list.c_GetMechanismList_list_val, (u_int *)&objp->c_GetMechanismList_list.c_GetMechanismList_list_len, ~0, sizeof(rpc_ck_mechanism_type_t), (xdrproc_t)xdr_rpc_ck_mechanism_type_t))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->c_GetMechanismList_count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetSessionInfo(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetSessionInfo *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetSessionInfo_rv))
		return (FALSE);
	if (!xdr_rpc_ck_session_info(xdrs, &objp->c_GetSessionInfo_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetMechanismInfo(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetMechanismInfo *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetMechanismInfo_rv))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism_info(xdrs, &objp->c_GetMechanismInfo_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GenerateRandom(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GenerateRandom *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GenerateRandom_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_GenerateRandom_data.c_GenerateRandom_data_val, (u_int *)&objp->c_GenerateRandom_data.c_GenerateRandom_data_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_FindObjects(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_FindObjects *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_FindObjects_rv))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->c_FindObjects_objects.c_FindObjects_objects_val, (u_int *)&objp->c_FindObjects_objects.c_FindObjects_objects_len, ~0, sizeof(rpc_ck_object_handle_t), (xdrproc_t)xdr_rpc_ck_object_handle_t))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->c_FindObjects_count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GenerateKey(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GenerateKey *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GenerateKey_rv))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->c_GenerateKey_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GenerateKeyPair(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GenerateKeyPair *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GenerateKeyPair_rv))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->c_GenerateKeyPair_pubhandle))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->c_GenerateKeyPair_privhandle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_CreateObject(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_CreateObject *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_CreateObject_rv))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->c_CreateObject_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_CopyObject(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_CopyObject *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_CopyObject_rv))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->c_CopyObject_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetAttributeValue(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetAttributeValue *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetAttributeValue_rv))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->c_GetAttributeValue_value))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetObjectSize(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetObjectSize *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetObjectSize_rv))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->c_GetObjectSize_size))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_WrapKey(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_WrapKey *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_WrapKey_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_WrapKey_value.c_WrapKey_value_val, (u_int *)&objp->c_WrapKey_value.c_WrapKey_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_UnwrapKey(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_UnwrapKey *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_UnwrapKey_rv))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->c_UnwrapKey_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_DeriveKey(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_DeriveKey *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_DeriveKey_rv))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->c_DeriveKey_handle))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_Digest(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_Digest *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_Digest_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_Digest_value.c_Digest_value_val, (u_int *)&objp->c_Digest_value.c_Digest_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_DigestFinal(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_DigestFinal *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_DigestFinal_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_DigestFinal_value.c_DigestFinal_value_val, (u_int *)&objp->c_DigestFinal_value.c_DigestFinal_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_Sign(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_Sign *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_Sign_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_Sign_value.c_Sign_value_val, (u_int *)&objp->c_Sign_value.c_Sign_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_SignFinal(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_SignFinal *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_SignFinal_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_SignFinal_value.c_SignFinal_value_val, (u_int *)&objp->c_SignFinal_value.c_SignFinal_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_Encrypt(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_Encrypt *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_Encrypt_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_Encrypt_value.c_Encrypt_value_val, (u_int *)&objp->c_Encrypt_value.c_Encrypt_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_EncryptUpdate(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_EncryptUpdate *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_EncryptUpdate_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_EncryptUpdate_value.c_EncryptUpdate_value_val, (u_int *)&objp->c_EncryptUpdate_value.c_EncryptUpdate_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_EncryptFinal(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_EncryptFinal *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_EncryptFinal_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_EncryptFinal_value.c_EncryptFinal_value_val, (u_int *)&objp->c_EncryptFinal_value.c_EncryptFinal_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_Decrypt(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_Decrypt *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_Decrypt_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_Decrypt_value.c_Decrypt_value_val, (u_int *)&objp->c_Decrypt_value.c_Decrypt_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_DecryptUpdate(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_DecryptUpdate *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_DecryptUpdate_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_DecryptUpdate_value.c_DecryptUpdate_value_val, (u_int *)&objp->c_DecryptUpdate_value.c_DecryptUpdate_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_DecryptFinal(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_DecryptFinal *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_DecryptFinal_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_DecryptFinal_value.c_DecryptFinal_value_val, (u_int *)&objp->c_DecryptFinal_value.c_DecryptFinal_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_SignRecover(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_SignRecover *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_SignRecover_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_SignRecover_value.c_SignRecover_value_val, (u_int *)&objp->c_SignRecover_value.c_SignRecover_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_VerifyRecover(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_VerifyRecover *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_VerifyRecover_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_VerifyRecover_value.c_VerifyRecover_value_val, (u_int *)&objp->c_VerifyRecover_value.c_VerifyRecover_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_DigestEncryptUpdate(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_DigestEncryptUpdate *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_DigestEncryptUpdate_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_DigestEncryptUpdate_value.c_DigestEncryptUpdate_value_val, (u_int *)&objp->c_DigestEncryptUpdate_value.c_DigestEncryptUpdate_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_DecryptDigestUpdate(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_DecryptDigestUpdate *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_DecryptDigestUpdate_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_DecryptDigestUpdate_value.c_DecryptDigestUpdate_value_val, (u_int *)&objp->c_DecryptDigestUpdate_value.c_DecryptDigestUpdate_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_SignEncryptUpdate(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_SignEncryptUpdate *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_SignEncryptUpdate_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_SignEncryptUpdate_value.c_SignEncryptUpdate_value_val, (u_int *)&objp->c_SignEncryptUpdate_value.c_SignEncryptUpdate_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_DecryptVerifyUpdate(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_DecryptVerifyUpdate *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_DecryptVerifyUpdate_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_DecryptVerifyUpdate_value.c_DecryptVerifyUpdate_value_val, (u_int *)&objp->c_DecryptVerifyUpdate_value.c_DecryptVerifyUpdate_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ck_rv_c_GetOperationState(xdrs, objp)
	XDR *xdrs;
	ck_rv_c_GetOperationState *objp;
{

	if (!xdr_rpc_ck_rv_t(xdrs, &objp->c_GetOperationState_rv))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->c_GetOperationState_value.c_GetOperationState_value_val, (u_int *)&objp->c_GetOperationState_value.c_GetOperationState_value_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_getslotlist_3_argument(xdrs, objp)
	XDR *xdrs;
	c_getslotlist_3_argument *objp;
{
	if (!xdr_pkcs11_int(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_login_3_argument(xdrs, objp)
	XDR *xdrs;
	c_login_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_user_type_t(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_opensession_3_argument(xdrs, objp)
	XDR *xdrs;
	c_opensession_3_argument *objp;
{
	if (!xdr_rpc_ck_slot_id_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_flags_t(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_getmechanismlist_3_argument(xdrs, objp)
	XDR *xdrs;
	c_getmechanismlist_3_argument *objp;
{
	if (!xdr_rpc_ck_slot_id_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_getmechanisminfo_3_argument(xdrs, objp)
	XDR *xdrs;
	c_getmechanisminfo_3_argument *objp;
{
	if (!xdr_rpc_ck_slot_id_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism_type_t(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_initpin_3_argument(xdrs, objp)
	XDR *xdrs;
	c_initpin_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_setpin_3_argument(xdrs, objp)
	XDR *xdrs;
	c_setpin_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_seedrandom_3_argument(xdrs, objp)
	XDR *xdrs;
	c_seedrandom_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_inittoken_3_argument(xdrs, objp)
	XDR *xdrs;
	c_inittoken_3_argument *objp;
{
	if (!xdr_rpc_ck_slot_id_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_generaterandom_3_argument(xdrs, objp)
	XDR *xdrs;
	c_generaterandom_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_findobjectsinit_3_argument(xdrs, objp)
	XDR *xdrs;
	c_findobjectsinit_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_findobjects_3_argument(xdrs, objp)
	XDR *xdrs;
	c_findobjects_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_pkcs11_int(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_generatekey_3_argument(xdrs, objp)
	XDR *xdrs;
	c_generatekey_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_generatekeypair_3_argument(xdrs, objp)
	XDR *xdrs;
	c_generatekeypair_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg3))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg4))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_createobject_3_argument(xdrs, objp)
	XDR *xdrs;
	c_createobject_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_copyobject_3_argument(xdrs, objp)
	XDR *xdrs;
	c_copyobject_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_destroyobject_3_argument(xdrs, objp)
	XDR *xdrs;
	c_destroyobject_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_getattributevalue_3_argument(xdrs, objp)
	XDR *xdrs;
	c_getattributevalue_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_setattributevalue_3_argument(xdrs, objp)
	XDR *xdrs;
	c_setattributevalue_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_getobjectsize_3_argument(xdrs, objp)
	XDR *xdrs;
	c_getobjectsize_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_wrapkey_3_argument(xdrs, objp)
	XDR *xdrs;
	c_wrapkey_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg4))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_unwrapkey_3_argument(xdrs, objp)
	XDR *xdrs;
	c_unwrapkey_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg4))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg5))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_derivekey_3_argument(xdrs, objp)
	XDR *xdrs;
	c_derivekey_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	if (!xdr_rpc_ck_attribute_array(xdrs, &objp->arg4))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_digestinit_3_argument(xdrs, objp)
	XDR *xdrs;
	c_digestinit_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_digest_3_argument(xdrs, objp)
	XDR *xdrs;
	c_digest_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_digestupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_digestupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_digestkey_3_argument(xdrs, objp)
	XDR *xdrs;
	c_digestkey_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_signinit_3_argument(xdrs, objp)
	XDR *xdrs;
	c_signinit_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_sign_3_argument(xdrs, objp)
	XDR *xdrs;
	c_sign_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_signupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_signupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_verifyinit_3_argument(xdrs, objp)
	XDR *xdrs;
	c_verifyinit_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_verify_3_argument(xdrs, objp)
	XDR *xdrs;
	c_verify_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_verifyupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_verifyupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_verifyfinal_3_argument(xdrs, objp)
	XDR *xdrs;
	c_verifyfinal_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_encryptinit_3_argument(xdrs, objp)
	XDR *xdrs;
	c_encryptinit_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_encrypt_3_argument(xdrs, objp)
	XDR *xdrs;
	c_encrypt_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_encryptupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_encryptupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_decryptinit_3_argument(xdrs, objp)
	XDR *xdrs;
	c_decryptinit_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_decrypt_3_argument(xdrs, objp)
	XDR *xdrs;
	c_decrypt_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_decryptupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_decryptupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_signrecoverinit_3_argument(xdrs, objp)
	XDR *xdrs;
	c_signrecoverinit_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_signrecover_3_argument(xdrs, objp)
	XDR *xdrs;
	c_signrecover_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_verifyrecoverinit_3_argument(xdrs, objp)
	XDR *xdrs;
	c_verifyrecoverinit_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_rpc_ck_mechanism(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_verifyrecover_3_argument(xdrs, objp)
	XDR *xdrs;
	c_verifyrecover_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_digestencryptupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_digestencryptupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_signencryptupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_signencryptupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_decryptdigestupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_decryptdigestupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_decryptverifyupdate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_decryptverifyupdate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_c_setoperationstate_3_argument(xdrs, objp)
	XDR *xdrs;
	c_setoperationstate_3_argument *objp;
{
	if (!xdr_rpc_ck_session_handle_t(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_opaque_data(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg3))
		return (FALSE);
	if (!xdr_rpc_ck_object_handle_t(xdrs, &objp->arg4))
		return (FALSE);
	return (TRUE);
}
